### ISSUE TITLE
Кнопка проигрывания заменяется на стандартную после редактирования аудиозаписи, например при добавлении к ней (записи) слов.

### ISSUE THREAD

**Issue by Mo-og** [icw82/kenzo-vk#3]
![screenshot_448930724000000](https://cloud.githubusercontent.com/assets/26124396/23480404/6ff57a22-fed0-11e6-9c8c-b653343de7fc.png)

**Comment by icw82** [comment]
В версии 5.4.1 такое поведение не наблюдается.
