### ISSUE TITLE
При удалении трека нет визуальных изменений

### ISSUE THREAD

**Issue by AlSoEdit** [icw82/kenzo-vk#38]
В интерфейсе без расширения удаленный трек становится "бледным"

![image](https://user-images.githubusercontent.com/14929897/27507496-fdffc9f8-58e9-11e7-9867-898ee4e2856c.png)
![image](https://user-images.githubusercontent.com/14929897/27507502-0df7a236-58ea-11e7-8c54-06ff69f654d0.png)

**Comment by icw82** [comment]
Спасибо, поправлю.

**Comment by icw82** [comment]
Исправлено в 5.4.2+
