### ISSUE TITLE
Something wrong with encodings

### ISSUE THREAD

**Issue by mohaxspb** [icw82/kenzo-vk#42]
Titles encoding seems to be broken.

![default](https://user-images.githubusercontent.com/9077598/29535022-f28a3216-86c0-11e7-8f78-b78b84edff20.JPG)

Also, when I donwload mp3 files with russian titles I see `крякозябры` instead of russian symbols while send them via telegram

**Comment by icw82** [comment]
Исправлено в версии 5.5.2+
